language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t ajaytikare/docker-cockroach -f Dockerfile.dev .

script:
    - docker run -e CI=true ajaytikare/docker-cockroach npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-cockroach"
    env: "DockerCockroach-env"
    bucket_name: "elasticbeanstalk-us-east-2-515113502899"
    bucket_path: "docker-cockroach"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

